
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"
      - cd  eureka
      - mvn compile
      - mvn package
      - echo "Building the docker image"
      - docker build -t service/cde-011-audit-eureka .
      - docker tag service/emp-rest-app $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cde-011-eureka-service-registry:cde-011-audit-eureka

  post_build:
    commands:
      - echo "Post_build"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cde-011-eureka-service-registry:cde-011-audit-eureka
      - printf '[{"name":"cde-011-audit-eureka-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cde-011-eureka-service-registry:cde-011-audit-eureka > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
    - eureka/taskdefinition.json